# encoding: UTF-8
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: utf-8
#title: 
email: frederic.vogt@alumni.anu.edu.au
description: > # this means to ignore newlines until "baseurl:"
  E0102-VR: an experimental VR application for observational astronomy.
baseurl: "http://fpavogt.github.io/E0102-VR" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: 
github_username:  fpavogt
skype_username: frederic.vogt
orcid_id: orcid.org/0000-0002-9665-2788

# Build settings
markdown: kramdown
